const languages = {
  FR: 'French',
  JP: 'Japanese',
  BR: 'Portuguese',
  AU: 'English',
  EG: 'Arabic',
  IT: 'Italian',
  CA: 'English',
  DE: 'German',
  IN: 'Hindi',
  MX: 'Spanish',
  ZA: 'English',
  ES: 'Spanish',
  GB: 'English',
  US: 'English',
  CN: 'Chinese',
  RU: 'Russian',
  AR: 'Spanish',
  NL: 'Dutch',
  SE: 'Swedish',
  CH: 'German',
  KR: 'Korean',
  PT: 'Portuguese',
  GR: 'Greek',
  TR: 'Turkish',
  NZ: 'English',
  IL: 'Hebrew',
  AE: 'Arabic',
  SG: 'English',
  PE: 'Spanish',
  MA: 'Arabic',
  CZ: 'Czech',
  AT: 'German',
  HR: 'Croatian',
  RO: 'Romanian',
  TH: 'Thai',
  HK: 'Chinese',
  ID: 'Indonesian',
  VN: 'Vietnamese',
  CL: 'Spanish',
  CO: 'Spanish',
  TZ: 'Swahili',
  KE: 'Swahili',
  GH: 'English',
  SN: 'French'
};


  export default languages;